### ISSUE TITLE
Error: missing dependency libmypaint >= 1.3.0 whan build Gimp-git

### ISSUE THREAD

**Issue by fabrixx** [mypaint/libmypaint#105]
Tryed renaming & linking with several names ( so.0.0--->so.0-->so). Tryed also 2.0 from git same error

Error: GIMP configuration failed.

  - Error: missing dependency libmypaint >= 1.3.0

See the file 'INSTALL' for more help.

------------------------------------------------------------------------------------------------------------
$ ldconfig -p | grep libmypaint
	libmypaint-1.3.so.0 (libc6,x86-64) => /usr/lib/libmypaint-1.3.so.0
	libmypaint-1.3.so (libc6,x86-64) => /usr/lib/libmypaint-1.3.so

**Comment by odysseywestra** [comment]
You probably have to take it up with the gimp-git package maintainer since we don't maintain the libmypaint 1.3 package on the AUR. I maintain the mypaint-git and libmypaint-git AUR packages though.

**Comment by achadwick** [comment]
@fabrixx 
Please check the output of `pkg-config --libs --cflags libmypaint-2.0`.

If it's an error message, then you have a broken `libmypaint-2.0` install. If it's a pile of compiler and linker flags, then it's a `gimp-git` screwup.

**Comment by achadwick** [comment]
Closing for now, since this doesn't appear to be a libmypaint issue at first blush. It's possible I'm wrong, because I don't have enough info to be going on.

@fabrixx, if you're following our install instructions fully, and this is still happening, and pkg-config is giving unusable output, then it's ours after all. Please yell at us to get it fixed here :smile:

**Comment by fabrixx** [comment]
Fixed with pkgconfig. Not Libmypaint error. For me is closed
