### ISSUE TITLE
consider tagging a new git point release

### ISSUE THREAD

**Issue by anthraxx** [mypaint/libmypaint#124]
Hi, the latest release is quite old and it would be awesome distro wise to get a new release so patches like the versioned library names don't need to be backported on top of the release from 2016.

**Comment by jplloyd** [comment]
@anthraxx @palob @alexmyczko @jbicha @myfreeweb

Seeking some opinions from packagers/maintainers on the [upcoming 1.5.0 release](https://github.com/mypaint/libmypaint/releases/tag/v1.5.0-beta.0), because I have basically no experience in these matters.

Do you have any opinion on which ABI the 1.5.0 release should be compatible with, if it indeed matters at all? I guess it's more logical to retain compatibility with 1.4.0 since it's more recent, though there are almost certainly more binaries (specifically GIMP) that are built against the 1.3.0 headers.

Like I wrote in the release notes, libmypaint uses the libtool `--release` flag, which is maybe relevant?

Changing the enum order (generated from a json, which is probably why the break in 1.4.0 wasn't picked up on) to be compatible with 1.4.0 does not take long.

**Comment by myfreeweb** [comment]
We (FreeBSD Ports) are fine with ABI changes, we can always rebuild the consumers. Happy to see that the plan is to have the same 1.x API that would work for both GIMP and MyPaint.

BTW, [ABI Laboratory's Tracker](https://abi-laboratory.pro/index.php?view=tracker) is really good for catching the kind of thing that happened with 1.4.0

**Comment by jplloyd** [comment]
Good to hear. I will wait a couple of days in case other distro packagers have any opinions. I have prepared (and verified) a for a 1.4.0-ABI-compatible release, just in case. It will be one or the other of course.

Thanks for the tip. I did in fact use the latest version of the [abi-compliance-checker](https://github.com/lvc/abi-compliance-checker) to verify the compatibility.

**Comment by anthraxx** [comment]
We are fine with ABI changes as well, that mostly just means some rounds of rebuilds. As long as the sonames are properly maintained and indicate incompatibility this is very easily done and detected during packaging time.
Bigger API related changes are more problematic, if they would break other downstream projects depending on libmypain like GIMP this would lead to the need of those projects to include API fixing patches.

**Comment by jplloyd** [comment]
@anthraxx Thank you. When I noticed the 1.4.0 ABI break a couple of weeks ago, I didn't realize that the `-release` flag was used (`libmypaint-major.minor`). So am I correct in assuming that the ABI incompatibility _and_ the unchanged ABI version fields are actually of no concern, since the SONAME's are different for any change to the minor version (`libmypaint-1.x.so.0` for x in {3, 4, 5} in this case)?

I don't quite understand why we use `-version-info` in conjunction with `-release`. It seems to me like the version info would only ever be relevant for ABI-breaking changes in a micro/patch-level release. I guess it's good to have it covered, even though that kind of change seems unlikely.

**Comment by jplloyd** [comment]
Minor point release [1.5.0](https://github.com/mypaint/libmypaint/releases/tag/v1.5.0) tagged.
