### ISSUE TITLE
Weblate entegration has been broken

### ISSUE THREAD

**Issue by libreajans** [mypaint/libmypaint#145]
I have updated some libmypaint strings several months ago. But, Turkish translation looks the same.

**Comment by jplloyd** [comment]
I don't know for sure, but I don't think integration was ever set up for either the libmypaint or mypaint repositories. Although it would be convenient, issue #146 is one reason for not setting up automatic pushing without review.

Once that situation is dealt with, I will merge the new translations (bit of a shame we didn't get it done by the 1.4 release).

**Comment by jplloyd** [comment]
Your translations are now merged. I'm not sure if we'll set up automatic pushing of translations, but I will write some documentation for developers on how to merge/rebase and otherwise sync up the weblate translations, so that the syncing interval will be shorter and the sync themselves more manageable.
