### ISSUE TITLE
Consider cleaning up doc/Doxyfile

### ISSUE THREAD

**Issue by hosiet** [mypaint/libmypaint#172]
The current Doxyfile was written back in 2012 with literally no change over these years. It contains some deprecated instructions that is starting to cause troubles when used together with modern Doxygen.

A recent issue was raised in downstream Debian via a bug report: https://bugs.debian.org/955099 , showing that libmypaint would fail to build when using the new Doxygen 2.4. Though later figured out that the build failure can be circumvented, I think it's time to really clean up the old Doxyfile. Maybe an upgrade using "doxygen -u" could be enough.

**Comment by jplloyd** [comment]
As I indicated in my comment on the debian tracker, the _Sphinx_ 2.4 build problem is not due to the Doxyfile, but to the sphinx extension that reads the doxygen output.

Whether we should keep using that extension (breathe) is a different question, but the issue was ultimately down to _not_ upgrading the dependency that itself depends on the thing that _was_ upgraded.

At any rate, the Doxyfile still definitely needed to be cleaned up. It is now\*  updated and the docs are built correctly and without warnings with the latest Doxygen/Sphinx/breathe.

\* (b9b00949027a2f635cd59c9a02c79c9cd98ae7d0 .. 6c5492b0af066a93b418d2f17bedc1a61ee1358e)
