### ISSUE TITLE
Tag and release libmypaint

### ISSUE THREAD

**Issue by ryandesign** [mypaint/libmypaint#22]
When will there be a specific version number of libmypaint tagged and released? libmypaint is a dependency of some other programs/libraries; one needs to be able to refer to a specific version number of libmypaint.

**Comment by achadwick** [comment]
At the moment it's not versioned independently of MyPaint, and it doesn't really have a separate development cycle. That can change, but at the same time it should become an officially completely independent library rather than continuing the submodule/static mess MyPaint currently uses.

My hope is that distributions like Debian, MSYS2 etc. should end up with independent libmypaint binary packages. @jonnor has done a ton of really good work here that I've been neglecting horribly in a haze of GTK3 nonsense, and I want that not to be lost.

"After MyPaint 1.2.0 releases" would be a good point for a formal split, given that libmypaint is [gathering translations](https://hosted.weblate.org/projects/mypaint/libmypaint/) to make it ready for the (MyPaint) 1.2.0 release. MyPaint itself will join it on hosted WebLate hopefully: see mypaint/mypaint#348 for updates. Getting the translations updated together will probably be healthy for both projects, but I consider libmypaint to be string-frozen for now (at least, until its translated strings are in a state that MyPaint can release!)

So, apologies for the bottleneck. Hopefully it's not that much of a problem long term.

**Comment by nphilipp** [comment]
Hi, do you have a better idea when we can expect a libmypaint release? I've only seen a handful of code commits in the new year, is there anything specific holding it up?

**Comment by achadwick** [comment]
@nphilipp
Now shooting for the end of this month. Thank @jehan for the heavy lifting on this!

There is some fallout from this: I want to cobble together a Debian-style package as a new project [here](https://github.com/mypaint) for our [testing PPA](https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing), and a PKGBUILD for [MSYS2](https://msys2.github.io/) on Windows in [the package maint repo](https://github.com/Alexpux/MINGW-packages/) for that project. And mypaint itself will need to be retooled to make use of an independent libmypaint.

I'm going to tag the initial independent version v1.3.0. Its version might drift independently of mypaint itself or it might not, but I want to avoid any confusion at all with our 1.2.x releases.

**Comment by achadwick** [comment]
There may be a couple of code-only prereleases before then. Watch <https://github.com/mypaint/libmypaint/releases> for news.

**Comment by achadwick** [comment]
[libmypaint 1.3.0-beta.0](https://github.com/mypaint/libmypaint/releases/tag/v1.3.0-beta.0) is now up. It's only a prerelease, so I will close this tracker issue when we release properly.

**Comment by achadwick** [comment]
I think 1.3.0 is ready now. Any tidying-up needed, or patches I've missed? If not, let's get it out on Thursday 01 Nov.

**Comment by achadwick** [comment]
Done: https://github.com/mypaint/libmypaint/releases/tag/v1.3.0
