### ISSUE TITLE
Support for more lines of symmetry

### ISSUE THREAD

**Issue by achadwick** [mypaint/libmypaint#27]
As reported by @android272 in mypaint/mypaint#529, it would be nice to have more lines of symmetry. This may need brush engine support, because symmetry is currently implemented there.

We need to decide:
- How best to represent infinite lines of symmetry
- Whether it would be simpler to move symmetry support back into the MyPaint core, and have that manage axes and just fire lots of different brushes at the canvas.

(After the 1.2.0 release though, not now)

**Comment by gudvinr** [comment]
Maybe it's better to implement only 2 lines of symmetry (horizontal/vertical) but allow to unlock them from canvas rotation.

**Comment by android272** [comment]
You could have a horizontal symetry line that would act like the vertical one does now. You would be able to move it up and down like you can move the other one left and right and delete it. 

For the many lines of symetry or spider web symetry you could look at how Krita does it. There could be a drop down like how you can change brush pressure and fade that would allow you to input the number of lines of symetry and/Or you could have a "+" and "-" button next to the delete button to add and subtract lines. Also you should be able to move the center point on the canvas.

**Comment by achadwick** [comment]
Here's the libmypaint code that does symmetry and makes more dabs, if anyone wants to take a look at this: [mypaint-tiled-surface.c:604](https://github.com/mypaint/libmypaint/blob/851ada040807e29c4428095b1b75d55a8df2bf49/mypaint-tiled-surface.c#L604). It models a reflection in a specified X axis, and doing it at the dab level ensures that the painted shapes are exact mirrors.

What we want are multiple reflections around arbitrary lines, which is mathematically somewhat trickier.

UI concerns are best thrown over the wall to mypaint/mypaint#529.

**Comment by ShadowKyogre** [comment]
Code from Krita that's relevant for this: https://phabricator.kde.org/diffusion/KRITA/browse/master/plugins/tools/basictools/kis_tool_multihand.cpp

Anyway, so I started working on the backend code. It's mostly done, but I haven't prototyped code for snowflake symmetry yet. Normal rotational symmetry is implemented. Just need to actually do a test build in my VM before I publicly share the changes.

However, there's two main issues so far:

1. There are a few fields that're exclusive to rotational and snowflake symmetry. Those fields are:
    * number of symmetry lines
    * angle offset for the rotational symmetry lines (eg: you want the 0 degree line of a rotational symmetry line set to point downward)
    * If snowflake symmetry is merged with normal rotational symmetry, probably a boolean that says, "Mirror around rotational lines"
    * That being said, would fields that're for rotation mode best be dedicated to another function and/or struct to avoid API breakage? I'd think so, but I wanted to double-check with you.
2. We don't have tests for symmetry right now? Given the amount of modes we'll need to support, I think this is mandatory since we'll need to make sure the strokes not only end up at the right coordinates, but also get the correct angles applied to them.

**Comment by sagabundo** [comment]
But how about angle symetry line, will be very usefull,

**Comment by odysseywestra** [comment]
Closing since Pull Request #57 and mypaint/mypaint#720 has addressed and added this Feature. 

@sagabundo, could you open a new ticket on [MyPaint's Issue Tracker](https://github.com/mypaint/mypaint/issues) as a Feature Request for the Symmetry Tool?
