### ISSUE TITLE
Release 1.3.0-beta.1 missing file "doc/Doxyfile"?

### ISSUE THREAD

**Issue by hartwork** [mypaint/libmypaint#54]
Hi there!

It seems the release tarball of 1.3.0-beta.1 lacks file `doc/Doxyfile`.
it would be cool to have a re-release with that file so that packagers have a chance at building and installing documentation. Many thanks!

Best, Sebastian

**Comment by Jehan** [comment]
Doxyfile as well as source/conf.py and source/index.rst were added to the distribution with commit 3e783fa. Now the documentation can be installed from the tarball.

There are some files under doc/scripts/ and doc/images/ which were not added to the dist. They don't seem to block doc generation but are they needed somehow else (for instance are images displayed somewhere in the doc pages)?

If so these should be added as well. Otherwise the report can be closed.

**Comment by Jehan** [comment]
No answer on the other files. I guess they are not needed. Let's close. Don't hesitate to reopen or create another report if any of these other files were actually needed.
