### ISSUE TITLE
MyPaint Rendering differs between 1.1.0 and git version

### ISSUE THREAD

**Issue by AnTi-ArT** [mypaint/libmypaint#9]
I just installed the git version from [2014-08-06](https://aur.archlinux.org/packages/mypaint-git/)
And the Ramon-2B pencil looks a lot more blurry and smoothed:
![screenshot from 2014-08-26 11 23 22](https://cloud.githubusercontent.com/assets/6949092/4042746/afdc82c2-2d07-11e4-8a45-6eebeb47dd28.png)
The chicken is an old drawing, and even when picking the stroke directly from it, it looks not the same. To make sure, I redowloaded the ramon set.
When switching back to 1.1.0 the brush is correct again.

**Comment by Shnatsel** [comment]
Doesn't seem to have anything to do with antialiasing ("Pixel feather" setting). It is already set to 0 by default, increasing it has no effect on the bug. 

Here's a test for two different brush sizes - one affected by the bug, the other not affected:

![test](https://cloud.githubusercontent.com/assets/291257/15592553/c0330a8c-23b5-11e6-9836-7f5a036f2b54.png)

**Comment by achadwick** [comment]
Closing this because brush behaviour has now changed for other reasons, and we have chosen to break strict brush appearance conformance to prior versions. If someone with a stake in this has *updated test cases* for the new libmypaint master branch (or better still can pin the actual numerical oddity at play here and why it's happening, with reference to `git bisect`s!), please open a new issue about it, referencing this one as `mypaint/libmypaint#9`.

If people think it's worth declaring a compatibility break for this reason and going to 2.x, let us know.

See mypaint/mypaint#818 for the decision re backwards compatibility with previous versions' brush appearance.

**Comment by briend** [comment]
Just want to leave a note here that these issues can probably be tuned-away with the new base brush radius input, so that brushes can stay crispy even with some pixel feathering at various sizes, etc.
